version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
